// ============================================================
// JerseyFlow - Beispieldaten (neue Struktur: mehrere Trikots pro Kunde)
// ============================================================

import { Order } from "@/types/order";

export const sampleOrders: Order[] = [
  {
    id: "sample-1",
    createdAt: "2026-04-10T10:00:00.000Z",
    updatedAt: "2026-04-15T14:00:00.000Z",
    customerName: "Marco Bauer",
    whatsapp: "+49 176 12345678",
    isPaid: true,
    paymentDate: "2026-04-12T00:00:00.000Z",
    notes: "",
    jerseys: [
      {
        id: "j-1-1",
        club: "FC Barcelona",
        playerName: "Pedri",
        jerseyNumber: "8",
        size: "L",
        version: "Player Version",
        jerseyType: "Heimtrikot",
        purchasePrice: 38,
        sellingPrice: 65,
        isOrdered: true,
        hasArrived: true,
        isPickedUp: true,
        notes: "",
      },
      {
        id: "j-1-2",
        club: "FC Barcelona",
        playerName: "Yamal",
        jerseyNumber: "27",
        size: "M",
        version: "Fan Version",
        jerseyType: "Auswärtstrikot",
        purchasePrice: 25,
        sellingPrice: 50,
        isOrdered: true,
        hasArrived: true,
        isPickedUp: true,
        notes: "",
      },
    ],
  },
  {
    id: "sample-2",
    createdAt: "2026-04-12T11:00:00.000Z",
    updatedAt: "2026-04-12T11:00:00.000Z",
    customerName: "Lisa Wagner",
    whatsapp: "+49 177 87654321",
    isPaid: false,
    paymentDate: null,
    notes: "Bitte Beflockung kontrollieren",
    jerseys: [
      {
        id: "j-2-1",
        club: "Real Madrid",
        playerName: "Bellingham",
        jerseyNumber: "5",
        size: "M",
        version: "Fan Version",
        jerseyType: "Heimtrikot",
        purchasePrice: 25,
        sellingPrice: 50,
        isOrdered: true,
        hasArrived: true,
        isPickedUp: false,
        notes: "Nummer kontrollieren",
      },
    ],
  },
  {
    id: "sample-3",
    createdAt: "2026-04-18T09:30:00.000Z",
    updatedAt: "2026-04-18T09:30:00.000Z",
    customerName: "Tim Hofmann",
    whatsapp: "+49 151 11223344",
    isPaid: true,
    paymentDate: "2026-04-19T00:00:00.000Z",
    notes: "",
    jerseys: [
      {
        id: "j-3-1",
        club: "Bayern München",
        playerName: "Kane",
        jerseyNumber: "9",
        size: "XL",
        version: "Player Version",
        jerseyType: "Auswärtstrikot",
        purchasePrice: 40,
        sellingPrice: 70,
        isOrdered: true,
        hasArrived: false,
        isPickedUp: false,
        notes: "",
      },
      {
        id: "j-3-2",
        club: "Bayern München",
        playerName: "Müller",
        jerseyNumber: "25",
        size: "L",
        version: "Fan Version",
        jerseyType: "Heimtrikot",
        purchasePrice: 25,
        sellingPrice: 50,
        isOrdered: true,
        hasArrived: false,
        isPickedUp: false,
        notes: "",
      },
      {
        id: "j-3-3",
        club: "Deutschland",
        playerName: "",
        jerseyNumber: "",
        size: "XL",
        version: "Fan Version",
        jerseyType: "Heimtrikot",
        purchasePrice: 30,
        sellingPrice: 55,
        isOrdered: false,
        hasArrived: false,
        isPickedUp: false,
        notes: "Wartet noch auf Entscheidung",
      },
    ],
  },
  {
    id: "sample-4",
    createdAt: "2026-04-20T15:00:00.000Z",
    updatedAt: "2026-04-20T15:00:00.000Z",
    customerName: "Sophie Klein",
    whatsapp: "",
    isPaid: false,
    paymentDate: null,
    notes: "Wartet auf Rückennummer-Entscheidung",
    jerseys: [
      {
        id: "j-4-1",
        club: "Borussia Dortmund",
        playerName: "",
        jerseyNumber: "",
        size: "S",
        version: "Fan Version",
        jerseyType: "Heimtrikot",
        purchasePrice: 22,
        sellingPrice: 45,
        isOrdered: false,
        hasArrived: false,
        isPickedUp: false,
        notes: "",
      },
    ],
  },
  {
    id: "sample-5",
    createdAt: "2026-05-05T12:00:00.000Z",
    updatedAt: "2026-05-05T12:00:00.000Z",
    customerName: "Anna Schneider",
    whatsapp: "+49 172 99887766",
    isPaid: false,
    paymentDate: null,
    notes: "Dringend – braucht es bis zum 20. Mai",
    jerseys: [
      {
        id: "j-5-1",
        club: "Arsenal FC",
        playerName: "Saka",
        jerseyNumber: "7",
        size: "M",
        version: "Player Version",
        jerseyType: "Heimtrikot",
        purchasePrice: 42,
        sellingPrice: 75,
        isOrdered: true,
        hasArrived: false,
        isPickedUp: false,
        notes: "",
      },
    ],
  },
];
